site_name: Nome do Projeto
site_author: Henrique Morais
site_description: >-
  Esse projeto foi desenvolvido com o intuito de facilitar
  o trabalho de construir uma documentação. Portanto, espero
  que esse template seja usado para aumento de produtividade.
copyright: Copyright &copy; Henrique Morais

repo_name: rikemorais.template.python
repo_url: https://github.com/rikemorais/rikemorais.template.python
edit_uri: tree/main/docs

theme:
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    - scheme: default
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb
        name: Modo Noturno
    - scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Modo Claro

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - /javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings

extra:
  alternate:
    - name: PT
      link: /pt/
      lang: pt
    - name: EN
      link: /en/ 
      lang: en

nav:
  - Home: index.md
  - Projeto:
    - Funcionalidades: markdown/funcionalidades.md
