name: Code Quality Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install Formatting Tools
      run: |
        pip install isort black interrogate

    - name: Run iSort and Black
      run: |
        isort .
        black . || (echo "isort or black formatting issues found" && exit 1)

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8
      run: |
        flake8 || (echo "Flake8 issues found" && exit 1)
    
    - name: Run Interrogate
      run: |
        interrogate --quiet --fail-under 95
